// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLRequest) Reset() {
	*x = ShortURLRequest{}
	mi := &file_proto_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLRequest) ProtoMessage() {}

func (x *ShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLRequest.ProtoReflect.Descriptor instead.
func (*ShortURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShortURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLResponse) Reset() {
	*x = ShortURLResponse{}
	mi := &file_proto_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLResponse) ProtoMessage() {}

func (x *ShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLResponse.ProtoReflect.Descriptor instead.
func (*ShortURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type OriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Short         string                 `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginalURLRequest) Reset() {
	*x = OriginalURLRequest{}
	mi := &file_proto_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalURLRequest) ProtoMessage() {}

func (x *OriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalURLRequest.ProtoReflect.Descriptor instead.
func (*OriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *OriginalURLRequest) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type OriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginalURLResponse) Reset() {
	*x = OriginalURLResponse{}
	mi := &file_proto_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalURLResponse) ProtoMessage() {}

func (x *OriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalURLResponse.ProtoReflect.Descriptor instead.
func (*OriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *OriginalURLResponse) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_proto_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *BatchRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ResultUrl     string                 `protobuf:"bytes,2,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_proto_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchResponse) GetResultUrl() string {
	if x != nil {
		return x.ResultUrl
	}
	return ""
}

type ShortURLBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchRequest        `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLBatchRequest) Reset() {
	*x = ShortURLBatchRequest{}
	mi := &file_proto_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLBatchRequest) ProtoMessage() {}

func (x *ShortURLBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortURLBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *ShortURLBatchRequest) GetUrls() []*BatchRequest {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ShortURLBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShortURLBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchResponse       `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURLBatchResponse) Reset() {
	*x = ShortURLBatchResponse{}
	mi := &file_proto_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURLBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLBatchResponse) ProtoMessage() {}

func (x *ShortURLBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortURLBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *ShortURLBatchResponse) GetUrls() []*BatchResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsRequest) Reset() {
	*x = UserURLsRequest{}
	mi := &file_proto_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsRequest) ProtoMessage() {}

func (x *UserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsRequest.ProtoReflect.Descriptor instead.
func (*UserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *UserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type URLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Short         string                 `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	Original      string                 `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLsResponse) Reset() {
	*x = URLsResponse{}
	mi := &file_proto_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLsResponse) ProtoMessage() {}

func (x *URLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLsResponse.ProtoReflect.Descriptor instead.
func (*URLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *URLsResponse) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *URLsResponse) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type UserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URLsResponse        `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_proto_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLsResponse.ProtoReflect.Descriptor instead.
func (*UserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *UserURLsResponse) GetUrls() []*URLsResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shorts        []string               `protobuf:"bytes,1,rep,name=shorts,proto3" json:"shorts,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLsRequest) Reset() {
	*x = DeleteURLsRequest{}
	mi := &file_proto_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsRequest) ProtoMessage() {}

func (x *DeleteURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteURLsRequest) GetShorts() []string {
	if x != nil {
		return x.Shorts
	}
	return nil
}

func (x *DeleteURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLsResponse) Reset() {
	*x = DeleteURLsResponse{}
	mi := &file_proto_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsResponse) ProtoMessage() {}

func (x *DeleteURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteURLsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_grpc_proto protoreflect.FileDescriptor

const file_proto_grpc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/grpc.proto\x12\x04grpc\"<\n" +
	"\x0fShortURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x10ShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"*\n" +
	"\x12OriginalURLRequest\x12\x14\n" +
	"\x05short\x18\x01 \x01(\tR\x05short\"1\n" +
	"\x13OriginalURLResponse\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal\"X\n" +
	"\fBatchRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"U\n" +
	"\rBatchResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"result_url\x18\x02 \x01(\tR\tresultUrl\"W\n" +
	"\x14ShortURLBatchRequest\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.grpc.BatchRequestR\x04urls\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\x15ShortURLBatchResponse\x12'\n" +
	"\x04urls\x18\x01 \x03(\v2\x13.grpc.BatchResponseR\x04urls\"*\n" +
	"\x0fUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\fURLsResponse\x12\x14\n" +
	"\x05short\x18\x01 \x01(\tR\x05short\x12\x1a\n" +
	"\boriginal\x18\x02 \x01(\tR\boriginal\":\n" +
	"\x10UserURLsResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.grpc.URLsResponseR\x04urls\"D\n" +
	"\x11DeleteURLsRequest\x12\x16\n" +
	"\x06shorts\x18\x01 \x03(\tR\x06shorts\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\",\n" +
	"\x12DeleteURLsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\x85\x03\n" +
	"\tShortener\x129\n" +
	"\bShortURL\x12\x15.grpc.ShortURLRequest\x1a\x16.grpc.ShortURLResponse\x12-\n" +
	"\x04Ping\x12\x11.grpc.PingRequest\x1a\x12.grpc.PingResponse\x12H\n" +
	"\rShortURLBatch\x12\x1a.grpc.ShortURLBatchRequest\x1a\x1b.grpc.ShortURLBatchResponse\x12E\n" +
	"\x0eGetOriginalURL\x12\x18.grpc.OriginalURLRequest\x1a\x19.grpc.OriginalURLResponse\x12<\n" +
	"\vGetUserURLs\x12\x15.grpc.UserURLsRequest\x1a\x16.grpc.UserURLsResponse\x12?\n" +
	"\n" +
	"DeleteURLs\x12\x17.grpc.DeleteURLsRequest\x1a\x18.grpc.DeleteURLsResponseB\x0fZ\rinternal/grpcb\x06proto3"

var (
	file_proto_grpc_proto_rawDescOnce sync.Once
	file_proto_grpc_proto_rawDescData []byte
)

func file_proto_grpc_proto_rawDescGZIP() []byte {
	file_proto_grpc_proto_rawDescOnce.Do(func() {
		file_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_proto_rawDesc), len(file_proto_grpc_proto_rawDesc)))
	})
	return file_proto_grpc_proto_rawDescData
}

var file_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_grpc_proto_goTypes = []any{
	(*ShortURLRequest)(nil),       // 0: grpc.ShortURLRequest
	(*ShortURLResponse)(nil),      // 1: grpc.ShortURLResponse
	(*PingRequest)(nil),           // 2: grpc.PingRequest
	(*PingResponse)(nil),          // 3: grpc.PingResponse
	(*OriginalURLRequest)(nil),    // 4: grpc.OriginalURLRequest
	(*OriginalURLResponse)(nil),   // 5: grpc.OriginalURLResponse
	(*BatchRequest)(nil),          // 6: grpc.BatchRequest
	(*BatchResponse)(nil),         // 7: grpc.BatchResponse
	(*ShortURLBatchRequest)(nil),  // 8: grpc.ShortURLBatchRequest
	(*ShortURLBatchResponse)(nil), // 9: grpc.ShortURLBatchResponse
	(*UserURLsRequest)(nil),       // 10: grpc.UserURLsRequest
	(*URLsResponse)(nil),          // 11: grpc.URLsResponse
	(*UserURLsResponse)(nil),      // 12: grpc.UserURLsResponse
	(*DeleteURLsRequest)(nil),     // 13: grpc.DeleteURLsRequest
	(*DeleteURLsResponse)(nil),    // 14: grpc.DeleteURLsResponse
}
var file_proto_grpc_proto_depIdxs = []int32{
	6,  // 0: grpc.ShortURLBatchRequest.urls:type_name -> grpc.BatchRequest
	7,  // 1: grpc.ShortURLBatchResponse.urls:type_name -> grpc.BatchResponse
	11, // 2: grpc.UserURLsResponse.urls:type_name -> grpc.URLsResponse
	0,  // 3: grpc.Shortener.ShortURL:input_type -> grpc.ShortURLRequest
	2,  // 4: grpc.Shortener.Ping:input_type -> grpc.PingRequest
	8,  // 5: grpc.Shortener.ShortURLBatch:input_type -> grpc.ShortURLBatchRequest
	4,  // 6: grpc.Shortener.GetOriginalURL:input_type -> grpc.OriginalURLRequest
	10, // 7: grpc.Shortener.GetUserURLs:input_type -> grpc.UserURLsRequest
	13, // 8: grpc.Shortener.DeleteURLs:input_type -> grpc.DeleteURLsRequest
	1,  // 9: grpc.Shortener.ShortURL:output_type -> grpc.ShortURLResponse
	3,  // 10: grpc.Shortener.Ping:output_type -> grpc.PingResponse
	9,  // 11: grpc.Shortener.ShortURLBatch:output_type -> grpc.ShortURLBatchResponse
	5,  // 12: grpc.Shortener.GetOriginalURL:output_type -> grpc.OriginalURLResponse
	12, // 13: grpc.Shortener.GetUserURLs:output_type -> grpc.UserURLsResponse
	14, // 14: grpc.Shortener.DeleteURLs:output_type -> grpc.DeleteURLsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_grpc_proto_init() }
func file_proto_grpc_proto_init() {
	if File_proto_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_proto_rawDesc), len(file_proto_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpc_proto_goTypes,
		DependencyIndexes: file_proto_grpc_proto_depIdxs,
		MessageInfos:      file_proto_grpc_proto_msgTypes,
	}.Build()
	File_proto_grpc_proto = out.File
	file_proto_grpc_proto_goTypes = nil
	file_proto_grpc_proto_depIdxs = nil
}
